Presentacion/Controllers/FacturaController.cs
using Antlr.Runtime.Misc;
using NReco.PdfGenerator;
using OpenHtmlToPdf;
using Presentacion.Models;
using RazorEngine;
using RazorEngine.Compilation.ImpromptuInterface;
using SelectPdf;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;


namespace Presentacion.Controllers
{
    public class FacturaController : Controller
    {
        private SoloOneEntities db = new SoloOneEntities();
        // GET: Factura
        [Authorize]
        public ActionResult Index()
        {

            var fac = new FacturasDTO();
            fac.lineaProductoList = db.lineaProducto.Include(l => l.material).Include(l => l.repara).Include(l => l.utiliza).ToList();

            ViewBag.lis = db.lineaProducto.Include(l => l.material).Include(l => l.repara).Include(l => l.utiliza).ToList();
            ViewBag.idUsuario = new SelectList(db.usuario.Where(usu => usu.tipo == true), "idUsuario", "nombre");
            ViewBag.idMaterial = new SelectList(db.material, "idMaterial", "marca");
            ViewBag.idIncidencia = new SelectList(db.incidencia, "idIncidencia", "FullDescription");
            ViewBag.idRepara = new SelectList(db.repara, "idRepara", "descripcionAveria");
            ViewBag.idUtiliza = new SelectList(db.utiliza, "idUtiliza", "idUtiliza");
            return View(fac);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Index(FacturasDTO a, [Bind(Include = "idLineaProducto,numeroMaterial,precioMaterial,idUtiliza,idRepara,idMaterial")] lineaProducto lineaProducto)
        {

            if (ModelState.IsValid)
            {
                db.lineaProducto.Add(lineaProducto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idMaterial = new SelectList(db.material, "idMaterial", "marca", lineaProducto.idMaterial);
            ViewBag.idRepara = new SelectList(db.repara, "idRepara", "descripcionAveria", lineaProducto.idRepara);
            ViewBag.idUtiliza = new SelectList(db.utiliza, "idUtiliza", "idUtiliza", lineaProducto.idUtiliza);

            var fac = new FacturasDTO();
            fac.lineaProductoList = db.lineaProducto.Include(l => l.material).Include(l => l.repara).Include(l => l.utiliza).ToList();
            return View();
        }
        [Authorize]
        public ActionResult SeleccionIncidencia()
        {
            ViewBag.idIncidencia = new SelectList(db.incidencia.Where(i => i.estado.ToUpper().Equals("HECHO")), "idIncidencia", "FullDescription");
            return View();
        }
        [HttpPost]
        [Authorize]
        public ActionResult SeleccionIncidencia(int idIncidencia) {
            //List<GetDatosFacturaDesdeIncidencia_Result> x = db.GetDatosFacturaDesdeIncidencia(idIncidencia).ToList();
            //TempData["Datos"] = x;           
            return RedirectToAction("Facturar", new { id = idIncidencia });
        }
        [Authorize]
        public ActionResult Facturar(int id) {

            //List<GetDatosFacturaDesdeIncidencia_Result> x = (List<GetDatosFacturaDesdeIncidencia_Result>)TempData["Datos"];

            List<GetDatosFacturaDesdeIncidencia_Result> x = db.GetDatosFacturaDesdeIncidencia(id).ToList();
            var fac = new FacturasDTO();
            fac.datosPro = x.FirstOrDefault();
            fac.Inci.idIncidencia = id;
            fac.lineaProductoList = db.lineaProducto.Include(l => l.material).Include(l => l.repara).Include(l => l.utiliza).Where(l => l.idRepara == fac.datosPro.idRepara).ToList();
            fac.LineaPro = new lineaProducto();
            ViewBag.idMaterial = new SelectList(db.material, "idMaterial", "marca");
            ViewBag.idRepara = new SelectList(db.repara.Where(r => r.idRepara == fac.datosPro.idRepara), "idRepara", "descripcionAveria");
            var nueva = new List<MaterialDTO>();

            foreach (var item in db.material.ToList())
            {               
                var prueb = new MaterialDTO();
                prueb.idMaterial = item.idMaterial;
                prueb.precio = item.precio;
                nueva.Add(prueb);
            }
            fac.allMate = nueva;
            return View(fac);
        }
        [Authorize]
        public ActionResult SetLineas() {

            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult SetLineas([Bind(Include = "idLineaProducto,numeroMaterial,precioMaterial,idUtiliza,idRepara,idMaterial")] lineaProducto lineaProductos, int id)
        {
            var idIncidencia = db.repara.Where(r => r.idRepara == id).Select(x => x.idIncidencia).FirstOrDefault();
            if (ModelState.IsValid)
            {

                var precioMaterial = db.material.Where(mat => mat.idMaterial == lineaProductos.idMaterial).FirstOrDefault().precio;
                lineaProductos.precioMaterial = precioMaterial.ToString();
                lineaProductos.idRepara = id;
                lineaProductos.idUtiliza = 1;
                db.lineaProducto.Add(lineaProductos);
                db.SaveChanges();

                return RedirectToAction("Facturar", new { id = idIncidencia });



            }
            ViewBag.ErrorMessage = "Material y cantidad de material obligatorio";

            ViewBag.idMaterial = new SelectList(db.material, "idMaterial", "marca", lineaProductos.idMaterial);
            ViewBag.idRepara = new SelectList(db.repara, "idRepara", "descripcionAveria", lineaProductos.idRepara);
            ViewBag.idUtiliza = new SelectList(db.utiliza, "idUtiliza", "idUtiliza", lineaProductos.idUtiliza);
            return RedirectToAction("Facturar", new { id = idIncidencia });
        }

        [Authorize]
        public ActionResult CalculosTotalesFac(int id, string s = "")
        {
            FacturasDTO fac = DatosFactura(id);
            fac.PDF = false;            
            return View(fac);


        }
       
      
        //Para 

        [HttpPost]
        [Authorize]
        public ActionResult CalculosTotalesFac(int id) {

            FacturasDTO fac = DatosFactura(id);
            fac.PDF = false;
            return View(fac);
        }
        //Para imprimir pdf
        [Authorize]
        public ActionResult Pdf1(int idInci)
        {

            var x = new Rotativa.MVC.ActionAsPdf("CalculosTotalesFac", new { id = idInci }) { FileName = "Test.pdf" };
            var aa = x.BuildPdf(ControllerContext);
            FileResult fileResult = new FileContentResult(aa, "application/pdf");
            fileResult.FileDownloadName = "ThisMvcViewToPdf.pdf";
            return fileResult;
        }

        [Authorize]
        public ActionResult Pdf2(int idInci)
        {
            FacturasDTO fac = DatosFactura(idInci);
            fac.PDF = true;

            string htmlString = HtmlEnString("CalculosTotalesFac", fac);
            string baseUrl = Request.Url.GetLeftPart(UriPartial.Authority);

            // instantiate a html to pdf converter object
            HtmlToPdf converter = new HtmlToPdf();



            // create a new pdf document converting an url
            PdfDocument doc = converter.ConvertHtmlString(htmlString, baseUrl);

            // save pdf document
            byte[] pdf = doc.Save();

            // close pdf document
            doc.Close();

            var inci = db.incidencia.Where(incide => incide.idIncidencia == idInci).FirstOrDefault();
            inci.facPdf = pdf;
            db.SaveChanges();
            
            FileResult fileResult = new FileContentResult(pdf, "application/pdf");
            fileResult.FileDownloadName = "Document.pdf";
            return fileResult;           

        }
        [Authorize]
        public ActionResult Pdf3(int idInci)
        {

            FacturasDTO fac = DatosFactura(idInci);
            fac.PDF = true;
            string html = HtmlEnString("CalculosTotalesFac", fac);
            ViewData.Add("TxtHtmlCode", html);
            return View();
        }
        [Authorize]
        private FacturasDTO DatosFactura(int id)
        {
            List<GetLineasByIncidecia_Result> ListaLineas = db.GetLineasByIncidecia(id).ToList();
            GetDatosFacturaDesdeIncidencia_Result DatosGeneral = db.GetDatosFacturaDesdeIncidencia(id).FirstOrDefault();
            var fac = new FacturasDTO();
            fac.datosPro = DatosGeneral;
            fac.Inci.idIncidencia = id;
            fac.lineaProductoList = db.lineaProducto.Include(l => l.material).Include(l => l.repara).Include(l => l.utiliza).Where(l => l.idRepara == fac.datosPro.idRepara).ToList();
            var repa = db.repara.Where(rep => rep.idIncidencia == id).FirstOrDefault();
            var x = new lineaProducto();
            x.material = new material();
            x.material.marca = "Mano de obra";
            x.precioMaterial = repa.precioHora;
            x.numeroMaterial = repa.horasTrabajadas;
            fac.lineaProductoList.Add(x);
            var totalDeLinesMaterial = new Decimal();
            foreach (var item in ListaLineas)
            {
                totalDeLinesMaterial += (Decimal)item.PrecioTotalMaterial;

            }
            var totalMano = Convert.ToDecimal(repa.precioHora.Replace(".", ",")) * Convert.ToDecimal(repa.horasTrabajadas.Replace(".", ","));
            var totalMateMano = totalMano + totalDeLinesMaterial;
            var impuesto = 21;
            var PorcentajeImpuesto = (totalMateMano * impuesto) / 100;
            fac.porImpue = PorcentajeImpuesto;
            fac.totalMaterial = totalMateMano;
            fac.Total = totalMateMano + PorcentajeImpuesto;
            Random r = new Random();
            var numer = r.Next(0, 1000000);            
            fac.numFact = numer.ToString("000000");
            return fac;
        }
        [Authorize]

Presentacion/Controllers/ReparaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Presentacion.Models;

namespace Presentacion.Controllers
{
    public class ReparaController : Controller
    {
        private SoloOneEntities db = new SoloOneEntities();

        // GET: Repara
        [Authorize]
        public ActionResult Index()
        {
            var repara = db.repara.Include(r => r.incidencia).Include(r => r.usuario);
            return View(repara.ToList());
        }

        // GET: Repara/Details/5
        [Authorize]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            repara repara = db.repara.Find(id);
            if (repara == null)
            {
                return HttpNotFound();
            }
            return View(repara);
        }

        // GET: Repara/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.idIncidencia = new SelectList(db.incidencia.Where(inci => inci.estado.ToUpper() != "HECHO"), "idIncidencia", "descripcionIncidencia");
            ViewBag.idUsuario = new SelectList(db.usuario.Where(usu => usu.tipo == true), "idUsuario", "nombre");
            ViewBag.fechaHoy = DateTime.Now.ToShortDateString();
            return View();
        }

        // POST: Repara/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "idRepara,idUsuario,idIncidencia,idLineaProducto,descripcionAveria,fecha,horasTrabajadas,precioHora")] repara repara)
        {
            if (ModelState.IsValid)
            {
                repara.fecha = repara.fechaHoy;
                db.repara.Add(repara);
                db.SaveChanges();
                ActulizarEstadoIncidencia(repara.idIncidencia, true);
                return RedirectToAction("Index");
            }

            ViewBag.idIncidencia = new SelectList(db.incidencia, "idIncidencia", "descripcionIncidencia", repara.idIncidencia);
            ViewBag.idUsuario = new SelectList(db.usuario.Where(usu => usu.tipo == true), "idUsuario", "nombre");
            return View(repara);
        }

        // GET: Repara/Edit/5
        [Authorize]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            repara repara = db.repara.Find(id);
            if (repara == null)
            {
                return HttpNotFound();
            }            
            ViewBag.idIncidencia = new SelectList(db.incidencia, "idIncidencia", "descripcionIncidencia", repara.idIncidencia);
            ViewBag.idUsuario = new SelectList(db.usuario.Where(usu => usu.tipo == true), "idUsuario", "nombre");
            return View(repara);
        }

        // POST: Repara/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "idRepara,idUsuario,idIncidencia,idLineaProducto,descripcionAveria,fecha,horasTrabajadas,precioHora,fechaBuena")] repara repara)
        {
            if (ModelState.IsValid)
            {
                repara.fecha = repara.fechaBuena;
                db.Entry(repara).State = EntityState.Modified;
                db.SaveChanges();
                ActulizarEstadoIncidencia(repara.idIncidencia, true);
                return RedirectToAction("Index");
            }
            ViewBag.idIncidencia = new SelectList(db.incidencia, "idIncidencia", "descripcionIncidencia", repara.idIncidencia);
            ViewBag.idUsuario = new SelectList(db.usuario.Where(usu => usu.tipo == true), "idUsuario", "nombre");
            return View(repara);
        }

        // GET: Repara/Delete/5
        [Authorize]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            repara repara = db.repara.Find(id);
            if (repara == null)
            {
                return HttpNotFound();
            }
            return View(repara);
        }

        // POST: Repara/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(long id)
        {
            repara repara = db.repara.Find(id);
            db.repara.Remove(repara);
            db.SaveChanges();
            ActulizarEstadoIncidencia(repara.idIncidencia, false);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void ActulizarEstadoIncidencia(long id,bool estado) {
            var incidencias = db.incidencia.Where(x => x.idIncidencia == id).FirstOrDefault();
            if (estado)
            {
                incidencias.estado = "Hecho";
            }
            else 
            { 
                incidencias.estado = "Pendiente"; 
            }
            using (var datos = new SoloOneEntities())//conexion a la base de datos
            {   //cargamos todas las entidades para posteriormente gestionarlas
                
                datos.incidencia.AddOrUpdate(incidencias);
                datos.SaveChanges();
            }
        }
    }
}

Presentacion/Views/Shared/_AddLineas.cshtml
@model  Presentacion.Models.lineaProducto

<div class="form-group">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.numeroMaterial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.precioMaterial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.idMaterial)
            </th>

        </tr>

        <tr>
            <td>
                @Html.EditorFor(model => model.numeroMaterial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numeroMaterial, "", new { @class = "text-danger" })
            </td>
            <td>
                <span id="precio" class="price"></span>
            </td>
            <td>
                @Html.DropDownList("idMaterial", null, " ", htmlAttributes: new { @class = "form-control", @id = "material" })
                @Html.ValidationMessageFor(model => model.idMaterial, "", new { @class = "text-danger" })
            </td>

        </tr>
        <p>@ViewBag.ErrorMessage</p>

    </table>

    <div class="col-md-offset-9 col-md-3">
        <input type="submit" value="Agregar Linea producto" class="btn btn-info" id="activa" style="width:auto" />
    </div>
</div>

Presentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SoloOne</title>
    @*@Styles.Render("~/Content/css")*@
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/css/new-age.css" rel="stylesheet" />
</head>
<body>
    @if (Request.IsAuthenticated)
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("SoloOne", "Factu", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "Index", "Profile")</li>
                        <li>@Html.ActionLink("Ver Usuarios", "MostrarTodo", "Profile")</li>
                        <li>@Html.ActionLink("Incidencias", "Index", "Incidencia")</li>
                        <li>@Html.ActionLink("Materiales", "Index", "Material")</li>
                        <li>@Html.ActionLink("Facturacion", "SeleccionIncidencia", "Factura")</li>
                        <li>@Html.ActionLink("Resolver Incidencia", "Index", "Repara")</li>
                        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li><a href="/Home/CerrarSesion">Cerrar sesion </a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    }
    <div class="container body-content" id="contenidoMain" >
        @RenderBody()
        <hr />
    </div>
    <div id="pie">
        <footer id="foot">
            <p>&copy; @DateTime.Now.Year - Soloone.site</p>
            <ul class="list-inline">
                <li class="list-inline-item">
                    <a href="#">Facebook</a>
                </li>
                <li class="list-inline-item">
                    <a href="#">Twitter</a>
                </li>
                <li class="list-inline-item">
                    <a href="#">Instagram</a>
                </li>
            </ul>
        </footer>
    </div>
    <!-- Footer -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)



</body>
</html>

Presentacion/Views/Shared/_ListaDeLineas.cshtml
@model IEnumerable<Presentacion.Models.lineaProducto>
@using (Html.BeginForm())

{
    <div class="form-group">


        <table class="table" id="updateEsta">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.material.marca)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.repara.descripcionAveria)
                </th>
                <th>

                    @Html.DisplayNameFor(model => model.numeroMaterial)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.precioMaterial)
                </th>
                <th>

                </th>

            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.material.marca)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.repara.descripcionAveria)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.numeroMaterial)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.precioMaterial)
                    </td>
                    <td>
                        @Html.ActionLink("Borrar", "BorrarLinea", new { id = item.idLineaProducto, idRepa = item.idRepara}, new { @class = "Borrar" })
                    </td>

                </tr>
            }

        </table>

    </div>
}

@section scripts{
    <script defer>

        $(".Borrar").click(function (event) {
            if (!confirm('¿Seguro que quieres borrar esta linea?')) {
                event.preventDefault();
            }
        })
    </script>
}