Presentacion/Models/material.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public material()
        {
            this.lineaProducto = new HashSet<lineaProducto>();
            this.utiliza = new HashSet<utiliza>();
        }
    
        public long idMaterial { get; set; }
        public string marca { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string refencia { get; set; }
        public byte[] imgMaterial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lineaProducto> lineaProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<utiliza> utiliza { get; set; }
    }
}

Presentacion/Controllers/MaterialController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Presentacion.Models;

namespace Presentacion.Controllers
{
    public class MaterialController : Controller
    {
        private SoloOneEntities db = new SoloOneEntities();

        // GET: Material
        [Authorize]
        public ActionResult Index()
        {
            return View(db.material.ToList());
        }

        // GET: Material/Details/5
        [Authorize]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            material material = db.material.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            return View(material);
        }
        [Authorize]
        // GET: Material/Create
        public ActionResult Create()
        {
            ViewBag.ReferenciaBuena = String.Format("MM-{0}-CC", DateTime.Now.ToString("MMddyyyyhhmmssffftt"));
            return View();
        }

        // POST: Material/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "idMaterial,marca,precio,refencia,imgMaterial")] material material)
        {
            HttpPostedFileBase img = Request.Files[0];
            if (img.ContentLength == 0)
            {
                ModelState.AddModelError("Imagen", "Es necesario seleccionar una imaegen.");
                
            }
            else {
                if (img.FileName.EndsWith(".png") || img.FileName.EndsWith(".jpg"))
                {
                    WebImage img2 = new WebImage(img.InputStream);
                    material.imgMaterial = img2.GetBytes();
                }
                else
                {
                    ModelState.AddModelError("Imagen", "Solo imagenes con formato .jpg y .png.");
                }
            }
           
            if (ModelState.IsValid)
            {
                material.refencia = material.referenciaBuena;                
                db.material.Add(material);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(material);
        }

        // GET: Material/Edit/5
        [Authorize]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            material material = db.material.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            return View(material);
        }

        // POST: Material/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "idMaterial,marca,precio,refencia,imgMaterial")] material material)
        {
            byte[] imgActual = db.material.Find(material.idMaterial).imgMaterial; 
            string refe = db.material.Find(material.idMaterial).refencia;

            HttpPostedFileBase img = Request.Files[0];
            if (img.ContentLength == 0)
            {                
                material.imgMaterial = imgActual;
            }
            else {
                if (img.FileName.EndsWith(".png") || img.FileName.EndsWith(".jpg"))
                {
                    WebImage img2 = new WebImage(img.InputStream);
                    material.imgMaterial = img2.GetBytes();
                }
                else
                {
                    ModelState.AddModelError("Imagen", "Solo imagenes con formato .jpg y .png.");
                   
                    material.imgMaterial = imgActual;

                }
            }
           

            if (ModelState.IsValid)
            {
                material.refencia = refe;
                db.material.AddOrUpdate(material);
                db.SaveChanges();
                //db.Entry(material).State = EntityState.Modified;
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(material);
        }

        // GET: Material/Delete/5
        [Authorize]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            material material = db.material.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            return View(material);
        }

        // POST: Material/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(long id)
        {
            material material = db.material.Find(id);
            db.material.Remove(material);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult getImg(int id)
        {
            var material = db.material.Find(id);
            byte[] byteImg = material.imgMaterial;
            MemoryStream memoryStream = new MemoryStream(byteImg);
            Image img = Image.FromStream(memoryStream);

            memoryStream = new MemoryStream();
            img.Save(memoryStream, ImageFormat.Png);
            memoryStream.Position = 0;
            return File(memoryStream,"img/png");
        }

    }
}

Presentacion/Views/Material/Create.cshtml
@model Presentacion.Models.material

@{
    ViewBag.Title = "Crear Material";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Material",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>material</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.TextBoxFor(model => model.precio, new { type = "decimal", min = "0", step = "0.s01" })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.refencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">               
                @*@Html.EditorFor(model => model.referenciaBuena, new { htmlAttributes = new { @class = "form-control" } })*@
                @ViewBag.ReferenciaBuena
                @Html.ValidationMessageFor(model => model.refencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imgMaterial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.imgMaterial, new { htmlAttributes = new { @class = "form-control" } })*@
                <input name="imgload" type="file" />
                @Html.ValidationMessageFor(model => model.imgMaterial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a ver todos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Presentacion/Views/Material/Delete.cshtml
@model Presentacion.Models.material

@{
    ViewBag.Title = "Borrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>¿Seguro que quieres borrar este material?</h3>
<div>
    <h4>Material</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.refencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.refencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imgMaterial)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.imgMaterial)*@
            <img width="100" src="@Url.Action("getImg","Material",new { id = Model.idMaterial})" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-info" /> |
            @Html.ActionLink("Volver a ver todos", "Index")
        </div>
    }
</div>

Presentacion/Views/Material/Details.cshtml
@model Presentacion.Models.material

@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles</h2>

<div>
    <h4>Material</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.refencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.refencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imgMaterial)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.imgMaterial)*@
            <img width="100" src="@Url.Action("getImg","Material",new { id = Model.idMaterial})" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.idMaterial }) |
    @Html.ActionLink("Volver a ver todos", "Index")
</p>

Presentacion/Views/Material/Edit.cshtml
@model Presentacion.Models.material

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm("Edit", "Material", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Material</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idMaterial)

        <div class="form-group">
            @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.precio, new { htmlAttributes = new { @type = "number", @min = "0", @step = "0.01", @value = "0" } })*@
                @Html.TextBoxFor(model => model.precio, new { type = "decimal", min = "0", step = "0.s01" })

                @*@Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.refencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.refencia, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DisplayFor(model => model.refencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.refencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imgMaterial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.imgMaterial, new { htmlAttributes = new { @class = "form-control" } })*@
                <img width="100" src="@Url.Action("getImg","Material",new { id = Model.idMaterial})"  />
                <input name="imgload" type="file" />
                @Html.ValidationMessageFor(model => model.imgMaterial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a ver todos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Presentacion/Views/Material/Index.cshtml
@model IEnumerable<Presentacion.Models.material>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista Material</h2>

<p>
    @Html.ActionLink("Crear Material", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.refencia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.imgMaterial)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.marca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.refencia)
        </td>
        <td>

            @*@{

            var imgSrc = Convert.ToBase64String(item.imgMaterial);
        }
        <img src="data:image/jpeg;base64, @imgSrc" alt="xx" />*@
            <img width="100" src="@Url.Action("getImg","Material",new { id = item.idMaterial})" />
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.idMaterial }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.idMaterial }) |
            @Html.ActionLink("Borrar", "Delete", new { id=item.idMaterial })
        </td>
    </tr>
}

</table>